### ISSUE TITLE
How to run build and deploy it on firebase as hosting ?

### ISSUE THREAD

**Issue by islamahmedrunprof** [creativetimofficial/vue-argon-dashboard#11]
i have tried to  run this commands .. 
- npm run build / yarn build 
- firebase init 
- firebase deploy 

finally i got a blank page with errors in a console said 
app.css 404 
app.js 404 
and so on ..

**Comment by manuelizq** [comment]
I have problems with the built, you got some solution

**Comment by agtoncerqueira** [comment]
I also got the same problem then I solved change publicPath in vue.config.js:
publicPath: isProd ? "" : "",
But css styles doesn't working properly now..

**Comment by jharris8567** [comment]
Same Issue!! AHH!! I glad I found this issue before I bought this thing and converted my site to it.

**Comment by agtoncerqueira** [comment]
> Same Issue!! AHH!!
> 
> I commented out line 2 and 5 in vue.config.js and it seems to work? I did not find `isProd` anywhere else.

Dude, I solve my problem. I downloaded a new vue theme called CORE UI and replace SRC folder and another one that is used from Vue-argon theme and I advise you don't replace package.json just copy dependency of vue-argon and merge with Core ui in order to avoid error to deploy.
Try this tip, will work very well.
Any question send me email: contact@agtoncerqueira.net
Cheers!

**Comment by VIRGO96** [comment]
> I also got the same problem then I solved change publicPath in vue.config.js:
> publicPath: isProd ? "" : "",
> But css styles doesn't working properly now..

saved me life
